# Generated by Django 4.2.1 on 2023-06-04 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
                ('point', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5, verbose_name='Очки')),
                ('is_right', models.BooleanField(default=False, verbose_name='Правильный ли ответ')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Набранные очки')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
                ('level', models.CharField(choices=[('Легкий', 'Easy'), ('Средний', 'Average'), ('Сложный', 'Hard')], default='Средний', max_length=7, verbose_name='Уровень')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заглавие')),
                ('text', models.CharField(max_length=300, verbose_name='Описание')),
                ('type', models.CharField(choices=[('Лексика', 'Vocabulary'), ('Грамматика', 'Grammar'), ('Фразеология', 'Phraseology'), ('Глаголы', 'Verbs'), ('Тест уровня', 'Level')], default='Тест уровня', max_length=11, verbose_name='Тип')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('tasks', models.ManyToManyField(related_name='tests', to='main.task', verbose_name='Задания')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ResultAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_answers', to='main.answer', verbose_name='Ответ')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_answers', to='main.result', verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Ответ результата',
                'verbose_name_plural': 'Ответы результата',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='result',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='main.test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='main.task', verbose_name='Задание'),
        ),
    ]
